name: Continuous monitoring of distribution channels

on:
    workflow_dispatch:
    schedule:
      - cron: '*/10 * * * *'

permissions:
  id-token: write
  contents: read

jobs:
    smoke-tests:
        name: Run smoke tests
        runs-on: ${{ matrix.os }}
        
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-22.04]
                version: [netcoreapp3.1, net6.0]

        steps:
          - name: Checkout repository
            uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 #v2.7.0
            
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a #v4.3.1
            with:
               role-to-assume: ${{ secrets.AWS_INTEG_TEST_ROLE_ARN }}
               aws-region: us-east-1

          - name: Setup dotnet
            uses: actions/setup-dotnet@871f041373faaad213a635d9afb62905ec029bbb #v1.10.1
            with:
              dotnet-version: |
                3.1.x
                6.0.x

          - name: Install dependencies
            run: dotnet restore sdk/test/SmokeTests/AWSXRayRecorder.SmokeTests.csproj

          - name: Build tests
            run: dotnet build sdk/test/SmokeTests/AWSXRayRecorder.SmokeTests.csproj --configuration Release --no-restore

          - name: Run tests
            id: distribution-availability
            run: dotnet test sdk/test/SmokeTests/bin/Release/${{matrix.version}}/AWSXRayRecorder.SmokeTests.dll
            
          - name: Publish metric on X-Ray Dotnet SDK distribution availability
            if: ${{ always() }}
            run: |
              if [[ "${{ steps.distribution-availability.outcome }}" == "failure" ]]; then
                aws cloudwatch put-metric-data --metric-name XRayDotnetSDKDistributionUnavailability --dimensions failure=rate --namespace MonitorSDK --value 1 --timestamp $(date +%s)
              else
                aws cloudwatch put-metric-data --metric-name XRayDotnetSDKDistributionUnavailability --dimensions failure=rate --namespace MonitorSDK --value 0 --timestamp $(date +%s)
              fi
